# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
   lane:Bubble do
   gym(
   clean:true,
   scheme:"BubbleAnimation",
   workspace:"BubbleAnimation.xcworkspace",
   silent: true,
   export_method:"development",
   configuration:"Release",#环境
   output_directory:"./ipa", 
   output_name:"BubbleAnimation.ipa",
   export_options: {
        provisioningProfiles: {
          "com.hule.HabyChat" => "dev_"
        }
     }
   )
 end
end
